### PR TITLE
custom maxRedirects

### PR DESCRIPTION
**Pull request by jpizarrom**
use options.maxRedirects or 10 by default

### CODE REVIEW

**Comment by jpizarrom** [comment]
cc @pdelsol @vitorohe

**Comment by pdelsol** [comment]
how do you set options.maxRedirects?

**Comment by pdelsol** [comment]
I saw it on the other PR,

its ok :+1:

**Comment by jpizarrom** [comment]
it's passed in options in https://github.com/admetricks/andris9-resolver/blob/v0.1.12/lib/resolver.js#L20

**Pull request merged**
